# Basic text processing, data sources and corpora

<sup>This notebook is a part of Natural Language Processing class at the University of Ljubljana, Faculty for computer and information science. Please contact [slavko.zitnik@fri.uni-lj.si](mailto:slavko.zitnik@fri.uni-lj.si) for any comments.</sub>

## Short intro to NLTK

NLTK library organization ([modules](http://www.nltk.org/py-modindex.html)):

| Module |	Shortcuts |	Data Structures	| Interfaces|	NLP Pyramid|
|---|---|---|---|---|
|*nltk.stem*, *nltk.text*, *nltk.tokenize* | *word_tokenize*, *sent_tokenize* |	*str*, *nltk.Text* => *[str]* |	*StemmerI*, *TokenizerI* |	*Morphology* |
|*nltk.tag*, *nltk.chunk*|	*pos_tag*|	*[str]* => *[(str, tag)]*, *nltk.Tree*|	*TaggerI*, *ParserI*, *ChunkParserI*	|Syntax|
|*nltk.chunk*, *nltk.sem*|	*ne_chunk*|	*nltk.Tree*, *nltk.DependencyGraph*|	*ParserI*, *ChunkParserI*|	Semantics|
|*nltk.sem.drt*	|–|	*Expression*	|–|	Pragmatics|

An example passing the first three levels of the NLP Pyramid:

<img src="nlp-pyramid.png" width="30%" />

In [1]:
import nltk
nltk.download("averaged_perceptron_tagger")
nltk.download('averaged_perceptron_tagger_eng')
nltk.download("maxent_ne_chunker")
nltk.download('maxent_ne_chunker_tab')
nltk.download("words")
nltk.download("reuters")
nltk.download("gutenberg")
nltk.download("wordnet")
nltk.download("tagsets")
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('tagsets_json')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker_tab is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package reuters to /root/nltk_data...
[nltk_data]   Package reuters is already up-to-date!
[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Pa

True

In [2]:
from nltk import word_tokenize, pos_tag, ne_chunk
 
text = "John works at OBI." 
 
# Morphology Level
tokens = word_tokenize(text)
print("Tokens:", tokens)
 
# Syntax Level
tagged_tokens = pos_tag(tokens)
print("POS tagging:", tagged_tokens)
 
# Semantics Level
ner_tree = ne_chunk(tagged_tokens)
print("Light parsing:", ner_tree)

Tokens: ['John', 'works', 'at', 'OBI', '.']
POS tagging: [('John', 'NNP'), ('works', 'VBZ'), ('at', 'IN'), ('OBI', 'NNP'), ('.', '.')]
Light parsing: (S (PERSON John/NNP) works/VBZ at/IN (ORGANIZATION OBI/NNP) ./.)


When working with text data, a [Text object](http://www.nltk.org/api/nltk.html#nltk.text.Text) might be useful to use:

In [3]:
from nltk import Text
from nltk.corpus import reuters
 
text = Text(reuters.words())
 
print("Similar words to 'Monday':")
text.similar('Monday', 5)

print("\nCommon contexts to a list of words ('August', 'June'):")
text.common_contexts(['August', 'June'])

print("\nContexts of a word 'Monday':")
text.concordance('Monday')

Similar words to 'Monday':
april march friday february january

Common contexts to a list of words ('August', 'June'):
and_and in_the in_and last_the on_the last_when between_and in_to
last_that for_shipment in_because ended_shr from_to since_and and_at
last_to in_last for_to in_u in_they

Contexts of a word 'Monday':
Displaying 25 of 240 matches:
said . Trade Minister Saleh said on Monday that Indonesia , as the world ' s s
Reuters to clarify his statement on Monday in which he said the pact should be
 the 11 - member CPA which began on Monday . They said producers agreed that c
ief Burkhard Junger was arrested on Monday on suspicion of embezzlement and of
ween one and 1 . 25 billion dlrs on Monday and Tuesday . The spokesman said Mo
ay and Tuesday . The spokesman said Monday ' s float included 500 mln dlrs in 
s ranged from minus 500 mln dlrs on Monday , when cash letter errors at two ea
 a deficit on Thursday , Friday and Monday but held excess reserves on the fin
ed temporary reser

Working with n-grams (bigrams, trigrams) and collocations extraction (PMI is [Pointwise mutual information](https://en.wikipedia.org/wiki/Pointwise_mutual_information)):

In [4]:
import nltk
from nltk.collocations import *
bigram_measures = nltk.collocations.BigramAssocMeasures()
trigram_measures = nltk.collocations.TrigramAssocMeasures()
 
# Bigrams
finder = BigramCollocationFinder.from_words(nltk.corpus.reuters.words())
finder.apply_freq_filter(5)

print("\nBest 50 bigrams according to PMI:", finder.nbest(bigram_measures.pmi, 50))
 
# Trigrams
finder = TrigramCollocationFinder.from_words(nltk.corpus.reuters.words())
finder.apply_freq_filter(5)
 
print("\nBest 50 trigrams according to PMI:", finder.nbest(trigram_measures.pmi, 50))


Best 50 bigrams according to PMI: [('DU', 'PONT'), ('Keng', 'Yaik'), ('Kwik', 'Save'), ('Nihon', 'Keizai'), ('corenes', 'pora'), ('fluidized', 'bed'), ('Akbar', 'Hashemi'), ('Constructions', 'Telephoniques'), ('Elevator', 'Mij'), ('Entre', 'Rios'), ('Graan', 'Elevator'), ('JIM', 'WALTER'), ('Taikoo', 'Shing'), ('der', 'Vorm'), ('di', 'Clemente'), ('Borrowing', 'Requirement'), ('FOOTE', 'MINERAL'), ('Hawker', 'Siddeley'), ('JARDINE', 'MATHESON'), ('PRORATION', 'FACTOR'), ('Wildlife', 'Refuge'), ('Kohlberg', 'Kravis'), ('Almir', 'Pazzionotto'), ('Bankhaus', 'Centrale'), ('Corpus', 'Christi'), ('Kuala', 'Lumpur'), ('Maple', 'Leaf'), ('Stats', 'Oljeselskap'), ('Zoete', 'Wedd'), ('Neutral', 'Zone'), ('Tadashi', 'Kuranari'), ('Drawing', 'Rights'), ('EASTMAN', 'KODAK'), ('Martinez', 'Cuenca'), ('Mathematical', 'Applications'), ('Townsend', 'Thoresen'), ('Sector', 'Borrowing'), ('Hashemi', 'Rafsanjani'), ('Hossein', 'Mousavi'), ('Kitty', 'Hawk'), ('SLAUGHTER', 'GUESSTIMATES'), ('Task', 'Force

Conversion between different data formats:

In [5]:
from nltk import word_tokenize, pos_tag, ne_chunk
from nltk.tag import untag, str2tuple, tuple2str
from nltk.chunk import tree2conllstr, conllstr2tree, conlltags2tree, tree2conlltags
 
text = "John works at OBI."
 
tokens = word_tokenize(text)
print("Tokens: ", tokens)
 
tagged_tokens = pos_tag(tokens)
print("\nTagged tokens: ", tagged_tokens)
 
print("\nUntagged tokens", untag(tagged_tokens))
 
tagged_tokens = [tuple2str(t) for t in tagged_tokens] 
print("\nTagged tokens to strings:", tagged_tokens)
 
tagged_tokens = [str2tuple(t) for t in tagged_tokens]
print("\nTagged tokens from strings to tuples:",  tagged_tokens)
 
ner_tree = ne_chunk(tagged_tokens)
print("\nNER tree:", ner_tree)
 
iob_tagged = tree2conlltags(ner_tree)
print("\nIOB tagged tree:", iob_tagged)
 
ner_tree = conlltags2tree(iob_tagged)
print("\nBack to tree:", ner_tree)
 
tree_str = tree2conllstr(ner_tree)
print("\nTree as CoNLL string:\n", tree_str)
 
ner_tree = conllstr2tree(tree_str, chunk_types=('PERSON', 'ORGANIZATION'))
print("\nCoNLL string to tree:", ner_tree)
 

Tokens:  ['John', 'works', 'at', 'OBI', '.']

Tagged tokens:  [('John', 'NNP'), ('works', 'VBZ'), ('at', 'IN'), ('OBI', 'NNP'), ('.', '.')]

Untagged tokens ['John', 'works', 'at', 'OBI', '.']

Tagged tokens to strings: ['John/NNP', 'works/VBZ', 'at/IN', 'OBI/NNP', './.']

Tagged tokens from strings to tuples: [('John', 'NNP'), ('works', 'VBZ'), ('at', 'IN'), ('OBI', 'NNP'), ('.', '.')]

NER tree: (S (PERSON John/NNP) works/VBZ at/IN (ORGANIZATION OBI/NNP) ./.)

IOB tagged tree: [('John', 'NNP', 'B-PERSON'), ('works', 'VBZ', 'O'), ('at', 'IN', 'O'), ('OBI', 'NNP', 'B-ORGANIZATION'), ('.', '.', 'O')]

Back to tree: (S (PERSON John/NNP) works/VBZ at/IN (ORGANIZATION OBI/NNP) ./.)

Tree as CoNLL string:
 John NNP B-PERSON
works VBZ O
at IN O
OBI NNP B-ORGANIZATION
. . O

CoNLL string to tree: (S (PERSON John/NNP) works/VBZ at/IN (ORGANIZATION OBI/NNP) ./.)


## Sentence splitting

Generally, pretrained models are good enough for tokenization. You might encounter issues using them if you are working with a specific genre of text (e.g. technical with specific abbreviations) or working with an unsupported language.

NLTK by default uses *PunktSentenceTokenizer*, which is unsupervised trainable model. A simple scenario:

In [6]:
from nltk import sent_tokenize
 
sentence = "All FRI students could get a Msc. in Computer Science."
print("Sentences:", sent_tokenize(sentence))

Sentences: ['All FRI students could get a Msc.', 'in Computer Science.']


As the above obviously does not work correctly for us, let's train our model. Default *PunktSentenceTokenizer* is an implementation of [Unsupervised Multilingual Sentence Boundary Detection (Kiss and Strunk (2005)](https://www.aclweb.org/anthology/J06-4003/).

In [7]:
from nltk.tokenize.punkt import PunktSentenceTokenizer, PunktTrainer
from nltk.corpus import gutenberg
 
# 1. Prepare text data
text = ""
for file_id in gutenberg.fileids():
    text += gutenberg.raw(file_id)

# 2. Train the params
trainer = PunktTrainer()
trainer.INCLUDE_ALL_COLLOCS = True
trainer.train(text)
 
# 3. Instantiate the model
tokenizer = PunktSentenceTokenizer(trainer.get_params())

Now we can test again ...

In [8]:
sentences = "Mr. James told me Dr. Zitnik is not available today. I will go to his office hours."
 
print("Tokenized: ", tokenizer.tokenize(sentences))
print("\nLearned abbreviations:", tokenizer._params.abbrev_types)
 
from pprint import pprint
print("\nSplit decisions debugging:")
for decision in tokenizer.debug_decisions(sentences):
    pprint(decision)
    print('=' * 30)

Tokenized:  ['Mr. James told me Dr.', 'Zitnik is not available today.', 'I will go to his office hours.']

Learned abbreviations: {'treb', 'fran', 'ed', 'mal', 'p.h', 'laer', 'vat', 'ara', 'cai', 'm.d', 'pind', 'mac', 'g', 'hora', 'feb', 'ang', 'doct', 'macd', 'vol', 'n', 'f', 'cin', 's.w.f', 'gho', 'osr', 'malc', 'ant', 'u', 'l10', 'qu', 'mt', 'sw', 'k.c', 'hon', 'br', 'ami', 'u.s', 'p', 'burs', 'bap', 'a.d', 'lep', 'cassi', "'mr", 'ophe', 'xx', 'y.sey', 'rosin', 'fred', 'fla', 'sey', 'poe', 'esq', 'finsb', 'ple', 'n.e', 'ros', 'm.p', 'gent', 'cop', 'wm', 'cob', 'mes', 'ult', 'xxx', 'mss', 'talb', 'foh', 'moo', 'ave', 'clo', 'p.m', 'k', "'dr", 'v.e', 'b', 'jun', 'amb', 'brut', 'clit', 'polon', 'syw', 'ibid', 'dag', 'phil', 'ger', 'w', 'cic', 'por', 'dard', "'w", 'j', 'banq', 'a.s', 'luc', 'mur', 'hec', 'ely', 'guil', 'ser', 'm', 'gen', 'oct', 'ro', 'cath', 'pol', 'octa', 'cass', 'boa', 'o.r', 'len', 'dut', 'messa', 'calp', 'cas', 'p.s', 'prima', 'g.k', 'macb', 'ment', 'deci', 'cly', '

We can manually add abbreviations or other parameters to update the model.

In [9]:
tokenizer._params.abbrev_types.add('msc')
tokenizer._params.abbrev_types.add('dr')

sentence = "All FRI students could get a Msc. in Computer Science."
print("Tokenized:", tokenizer.tokenize(sentence))

sentences = "Mr. James told me Dr. Zitnik is not available today. I will go to his office hours."
print("Tokenized: ", tokenizer.tokenize(sentences))

Tokenized: ['All FRI students could get a Msc. in Computer Science.']
Tokenized:  ['Mr. James told me Dr. Zitnik is not available today.', 'I will go to his office hours.']


## Basic text processing tools

### Stemming

> In linguistic morphology and information retrieval, stemming is the process of reducing inflected (or sometimes derived) words to their word stem, base or root form—generally a written word form. The stem need not be identical to the morphological root of the word; it is usually sufficient that related words map to the same stem, even if this stem is not in itself a valid root. Algorithms for stemming have been studied in computer science since the 1960s. Many search engines treat words with the same stem as synonyms as a kind of query expansion, a process called conflation.

One of the first stemmers was designed by [Martin Porter](https://tartarus.org/martin/PorterStemmer/) (*M.F. Porter, 1980, An algorithm for suffix stripping, Program, 14(3), pp. 130−137*), which is a suffix stripping algorithm and most widely used. Later he continued his work and presented his improved work for English and for some other languages with the Snowball stemmer.

The NLTK includes some stemmer implementations - Porter, Lancaster, Snowball.

In [10]:
import nltk
import string

# Prepare text
def getTokens():
   with open('shakespeare.txt', 'r') as shakes:
    text = shakes.read().lower()
    # remove punctuation
    table = text.maketrans({key: None for key in string.punctuation})
    text = text.translate(table)      
    tokens = nltk.word_tokenize(text)
    return tokens

# Do stemming
from nltk.stem import SnowballStemmer
stemmer = SnowballStemmer("english")
stems = [(token, stemmer.stem(token)) for token in getTokens()]
stems[:50]

[('this', 'this'),
 ('young', 'young'),
 ('gentlewoman', 'gentlewoman'),
 ('had', 'had'),
 ('a', 'a'),
 ('fathero', 'fathero'),
 ('that', 'that'),
 ('had', 'had'),
 ('how', 'how'),
 ('sad', 'sad'),
 ('a', 'a'),
 ('passage', 'passag'),
 ('tiswhose', 'tiswhos'),
 ('skill', 'skill'),
 ('was', 'was'),
 ('almost', 'almost'),
 ('as', 'as'),
 ('great', 'great'),
 ('as', 'as'),
 ('his', 'his'),
 ('honesty', 'honesti'),
 ('had', 'had'),
 ('it', 'it'),
 ('stretched', 'stretch'),
 ('so', 'so'),
 ('far', 'far'),
 ('would', 'would'),
 ('have', 'have'),
 ('made', 'made'),
 ('nature', 'natur'),
 ('immortal', 'immort'),
 ('and', 'and'),
 ('death', 'death'),
 ('should', 'should'),
 ('have', 'have'),
 ('play', 'play'),
 ('for', 'for'),
 ('lack', 'lack'),
 ('of', 'of'),
 ('work', 'work'),
 ('would', 'would'),
 ('for', 'for'),
 ('the', 'the'),
 ('kings', 'king'),
 ('sake', 'sake'),
 ('he', 'he'),
 ('were', 'were'),
 ('living', 'live'),
 ('i', 'i'),
 ('think', 'think')]

### Lemmatisation

> Lemmatisation (or lemmatization) in linguistics is the process of grouping together the different inflected forms of a word so they can be analysed as a single item.

> In computational linguistics, lemmatisation is the algorithmic process of determining the lemma for a given word. Since the process may involve complex tasks such as understanding context and determining the part of speech of a word in a sentence (requiring, for example, knowledge of the grammar of a language) it can be a hard task to implement a lemmatiser for a new language.

> In many languages, words appear in several inflected forms. For example, in English, the verb 'to walk' may appear as 'walk', 'walked', 'walks', 'walking'. The base form, 'walk', that one might look up in a dictionary, is called the lemma for the word.

> Lemmatisation is closely related to stemming. The difference is that a stemmer operates on a single word without knowledge of the context, and therefore cannot discriminate between words which have different meanings depending on part of speech. However, stemmers are typically easier to implement and run faster, and the reduced accuracy may not matter for some applications.

In [11]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
lemmas = [lemmatizer.lemmatize(token) for token in getTokens()]
lemmas

['this',
 'young',
 'gentlewoman',
 'had',
 'a',
 'fathero',
 'that',
 'had',
 'how',
 'sad',
 'a',
 'passage',
 'tiswhose',
 'skill',
 'wa',
 'almost',
 'a',
 'great',
 'a',
 'his',
 'honesty',
 'had',
 'it',
 'stretched',
 'so',
 'far',
 'would',
 'have',
 'made',
 'nature',
 'immortal',
 'and',
 'death',
 'should',
 'have',
 'play',
 'for',
 'lack',
 'of',
 'work',
 'would',
 'for',
 'the',
 'king',
 'sake',
 'he',
 'were',
 'living',
 'i',
 'think',
 'it',
 'would',
 'be',
 'the',
 'death',
 'of',
 'the',
 'king',
 'disease',
 'he',
 'wa',
 'excellent',
 'indeed',
 'madam',
 'the',
 'king',
 'very',
 'lately',
 'spoke',
 'of',
 'him',
 'admiringly',
 'and',
 'mourningly',
 'he',
 'wa',
 'skilful',
 'enough',
 'to',
 'have',
 'lived',
 'still',
 'if',
 'knowledge',
 'could',
 'be',
 'set',
 'up',
 'against',
 'mortality',
 'his',
 'sole',
 'child',
 'my',
 'lord',
 'and',
 'bequeathed',
 'to',
 'my',
 'overlooking',
 'i',
 'have',
 'those',
 'hope',
 'of',
 'her',
 'good',
 'that',


In [12]:
# TODO: Find the differences between lemmas and stems

The function above finds a lemma expecting a noun by default, so we should also include a part-of-speech information, e.g., `lemmatizer.lemmatize("walking", pos='v')` for verbs - the default parameter is noun.

In [13]:
# TODO: Try to lemmatise is, are, was, were without and with pos parameter. Is there a difference?

### Part-of-speech tagging

> A part of speech (abbreviated form: PoS or POS) is a category of words (or, more generally, of lexical items) which have similar grammatical properties. Words that are assigned to the same part of speech generally display similar behavior in terms of syntax—they play similar roles within the grammatical structure of sentences—and sometimes in terms of morphology, in that they undergo inflection for similar properties. Commonly listed English parts of speech are noun, verb, adjective, adverb, pronoun, preposition, conjunction, interjection, and sometimes numeral, article or determiner.

In NLTK, there exist some implementations of taggers and possible tagsets ([source](http://www.nltk.org/_modules/nltk/tag.html#pos_tag)).

In [14]:
posTagged = nltk.pos_tag(getTokens())
posTagged[:50]

[('this', 'DT'),
 ('young', 'JJ'),
 ('gentlewoman', 'NN'),
 ('had', 'VBD'),
 ('a', 'DT'),
 ('fathero', 'NN'),
 ('that', 'WDT'),
 ('had', 'VBD'),
 ('how', 'WRB'),
 ('sad', 'JJ'),
 ('a', 'DT'),
 ('passage', 'NN'),
 ('tiswhose', 'NN'),
 ('skill', 'NN'),
 ('was', 'VBD'),
 ('almost', 'RB'),
 ('as', 'RB'),
 ('great', 'JJ'),
 ('as', 'IN'),
 ('his', 'PRP$'),
 ('honesty', 'NN'),
 ('had', 'VBD'),
 ('it', 'PRP'),
 ('stretched', 'VBD'),
 ('so', 'RB'),
 ('far', 'RB'),
 ('would', 'MD'),
 ('have', 'VB'),
 ('made', 'VBN'),
 ('nature', 'JJ'),
 ('immortal', 'JJ'),
 ('and', 'CC'),
 ('death', 'NN'),
 ('should', 'MD'),
 ('have', 'VB'),
 ('play', 'NN'),
 ('for', 'IN'),
 ('lack', 'NN'),
 ('of', 'IN'),
 ('work', 'NN'),
 ('would', 'MD'),
 ('for', 'IN'),
 ('the', 'DT'),
 ('kings', 'NNS'),
 ('sake', 'VBP'),
 ('he', 'PRP'),
 ('were', 'VBD'),
 ('living', 'VBG'),
 ('i', 'JJ'),
 ('think', 'VBP')]

By default, the Penn Treebank tags are used ([tagset](https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html)).

In [15]:
nltk.help.upenn_tagset("NNP") # Meaning of a specific tag with examples

NNP: noun, proper, singular
    Motown Venneboerger Czestochwa Ranzer Conchita Trumplane Christos
    Oceanside Escobar Kreisler Sawyer Cougar Yvette Ervin ODI Darryl CTCA
    Shannon A.K.C. Meltex Liverpool ...


### Documents comparison using TF-IDF

TF-IDF is a common metric in information retrieval which weights a term with respect to a list of documents.

> In information retrieval, tf–idf, short for term frequency–inverse document frequency, is a numerical statistic that is intended to reflect how important a word is to a document in a collection or corpus. It is often used as a weighting factor in information retrieval and text mining. The tf-idf value increases proportionally to the number of times a word appears in the document, but is offset by the frequency of the word in the corpus, which helps to adjust for the fact that some words appear more frequently in general.

> Variations of the tf–idf weighting scheme are often used by search engines as a central tool in scoring and ranking a document's relevance given a user query. tf–idf can be successfully used for stop-words filtering in various subject fields including text summarization and classification.

The metric is calculated as follows:

$$\textrm{TF}(term) = \frac{\textrm{Number of times term appears in a document}}{\textrm{Total number of terms in the document}}$$

$$\textrm{IDF}(term) = \frac{\textrm{Total number of documents}}{\textrm{Number of documents with the term in it}}$$

$$\textrm{TF-IDF}(term) = \textrm{TF}(term) * \log_e(\textrm{IDF}(term))$$

Computing TF-IDF scores for given documents:

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

vect = TfidfVectorizer() # parameters for tokenization, stopwords can be passed
tfidf = vect.fit_transform(["Halloween is scary!",
                            "People wear halloween masks.",
                            "There exist many masks and halloween pumpkins.",
                            "People build scary lantern pumpkins."])

print("TF-IDF vectors (each column is a document):\n{}\nRows:\n{}".format(np.asmatrix(tfidf.T.toarray()), vect.get_feature_names_out()))

TF-IDF vectors (each column is a document):
[[0.         0.         0.42068099 0.        ]
 [0.         0.         0.         0.50867187]
 [0.         0.         0.42068099 0.        ]
 [0.44809973 0.39205255 0.26851522 0.        ]
 [0.70203482 0.         0.         0.        ]
 [0.         0.         0.         0.50867187]
 [0.         0.         0.42068099 0.        ]
 [0.         0.4842629  0.33166972 0.        ]
 [0.         0.4842629  0.         0.40104275]
 [0.         0.         0.33166972 0.40104275]
 [0.55349232 0.         0.         0.40104275]
 [0.         0.         0.42068099 0.        ]
 [0.         0.61422608 0.         0.        ]]
Rows:
['and' 'build' 'exist' 'halloween' 'is' 'lantern' 'many' 'masks' 'people'
 'pumpkins' 'scary' 'there' 'wear']


Computing [cosine similarities](https://en.wikipedia.org/wiki/Cosine_similarity) for documents:

In [17]:
cosine = (tfidf * tfidf.T)
print("Cosine similarity between the documents: \n{}".format(np.asmatrix(cosine.toarray())))

Cosine similarity between the documents: 
[[1.         0.17567864 0.1203216  0.22197408]
 [0.17567864 1.         0.26588742 0.19421012]
 [0.1203216  0.26588742 1.         0.13301374]
 [0.22197408 0.19421012 0.13301374 1.        ]]


Comparing a new document (or searching) to the corpus:

In [18]:
weights = vect.transform(["Where to buy a halloween mask and pumpkins?"])

# HINT: If the text is completely different from the corpus, a zero vector will be returned
# and therefore also not printed.
print("New document:\n{}".format(np.asmatrix(weights.T.toarray()))) 

New document:
[[0.70203482]
 [0.        ]
 [0.        ]
 [0.44809973]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.55349232]
 [0.        ]
 [0.        ]
 [0.        ]]


In [19]:
# TODO: Try to calculate, which documents are the most similar to a query above

## Useful data sources/tools

When recognizing important parts of text, it is useful to help yourself with semantic databases or gazetteer lists (e.g., lists of organization names, countries, ...).

### WordNet

> WordNet is a lexical database for the English language. It groups English words into sets of synonyms called synsets, provides short definitions and usage examples, and records a number of relations among these synonym sets or their members. WordNet can thus be seen as a combination of dictionary and thesaurus. While it is accessible to human users via a web browser, its primary use is in automatic text analysis and artificial intelligence applications. The database and software tools have been released under a BSD style license and are freely available for download from the WordNet website. Both the lexicographic data (lexicographer files) and the compiler (called grind) for producing the distributed database are available.

Let's find all sets of synonyms for word `book`.

In [20]:
from nltk.corpus import wordnet
syns = wordnet.synsets("book")
syns

[Synset('book.n.01'),
 Synset('book.n.02'),
 Synset('record.n.05'),
 Synset('script.n.01'),
 Synset('ledger.n.01'),
 Synset('book.n.06'),
 Synset('book.n.07'),
 Synset('koran.n.01'),
 Synset('bible.n.01'),
 Synset('book.n.10'),
 Synset('book.n.11'),
 Synset('book.v.01'),
 Synset('reserve.v.04'),
 Synset('book.v.03'),
 Synset('book.v.04')]

Print out some data about these synsets.

In [21]:
for synset in syns:
    print("Syset name: '{}'".format(synset.name()))
    print("Lemmas:     '{}'".format([lemma.name() for lemma in synset.lemmas()]))
    print("Definition: '{}'".format(synset.definition()))
    print("Examples:   '{}'\n".format(synset.examples()))

Syset name: 'book.n.01'
Lemmas:     '['book']'
Definition: 'a written work or composition that has been published (printed on pages bound together)'
Examples:   '['I am reading a good book on economics']'

Syset name: 'book.n.02'
Lemmas:     '['book', 'volume']'
Definition: 'physical objects consisting of a number of pages bound together'
Examples:   '['he used a large book as a doorstop']'

Syset name: 'record.n.05'
Lemmas:     '['record', 'record_book', 'book']'
Definition: 'a compilation of the known facts regarding something or someone'
Examples:   '["Al Smith used to say, `Let's look at the record'", 'his name is in all the record books']'

Syset name: 'script.n.01'
Lemmas:     '['script', 'book', 'playscript']'
Definition: 'a written version of a play or other dramatic composition; used in preparing for a performance'
Examples:   '[]'

Syset name: 'ledger.n.01'
Lemmas:     '['ledger', 'leger', 'account_book', 'book_of_account', 'book']'
Definition: 'a record in which commercial a

Find synonyms, antonyms, hypernyms and hyponyms of a word `good`.

In [22]:
synonyms = []
antonyms = []
hypernyms = []
hyponyms = []

for synset in wordnet.synsets("good"):
    for lemma in synset.lemmas():
        synonyms.append(lemma.name())
        if lemma.antonyms():
            antonyms.append(lemma.antonyms()[0].name())
        if synset.hypernyms():
            hypernyms.append(synset.hypernyms()[0].name())
        if synset.hyponyms():
            hyponyms.append(synset.hyponyms()[0].name())

print("Synonyms:  '{}'\n".format(set(synonyms)))
print("Antonyms:  '{}'".format(set(antonyms)))
print("Hypernyms: '{}'".format(set(hypernyms)))
print("Hyponyms:  '{}'".format(set(hyponyms)))

Synonyms:  '{'in_force', 'salutary', 'practiced', 'commodity', 'dear', 'secure', 'estimable', 'undecomposed', 'dependable', 'well', 'proficient', 'honorable', 'honest', 'in_effect', 'unspoiled', 'thoroughly', 'expert', 'adept', 'respectable', 'skillful', 'soundly', 'trade_good', 'ripe', 'upright', 'safe', 'goodness', 'right', 'effective', 'skilful', 'beneficial', 'serious', 'good', 'full', 'just', 'near', 'unspoilt', 'sound'}'

Antonyms:  '{'evilness', 'bad', 'badness', 'evil', 'ill'}'
Hypernyms: '{'artifact.n.01', 'morality.n.01', 'advantage.n.01', 'quality.n.01'}'
Hyponyms:  '{'fancy_goods.n.01', 'summum_bonum.n.01', 'common_good.n.01', 'better.n.01'}'


Compare similarity of two synsets.

The Wu & Palmer measure calculates relatedness by considering the depths of the two synsets in the WordNet taxonomies, along with the depth of the LCS (Least Common Subsumer). The formula is score = 2*depth(lcs) / (depth(s1) + depth(s2)). This means that 0 < score <= 1. The score can never be zero because the depth of the LCS is never zero (the depth of the root of a taxonomy is one). The score is one if the two input synsets are the same.

In [23]:
good = wordnet.synsets("good")[0]
nice = wordnet.synsets("nice")[0]
bad  = wordnet.synsets("bad")[0]

print("Good vs. nice: {:.2}".format(good.wup_similarity(nice)))
print(" Good vs. bad: {:.2}".format(good.wup_similarity(bad)))

Good vs. nice: 0.12
 Good vs. bad: 0.67


### Other sources

A plethora of other data sources exist, for example:

* [VerbNet](http://verbs.colorado.edu/~mpalmer/projects/verbnet.html)
* [FrameNet](https://framenet.icsi.berkeley.edu/fndrupal/)
* [SentiStrength](http://sentistrength.wlv.ac.uk/)
* [BabelNet](http://babelnet.org/)
* [ConceptNet](http://www.conceptnet.io/)


## Corpora

To train or test an NLP system, we need some tagged data to compare the systems to. Some datasets exist from challenges, for example:

* [CoNLL](http://www.conll.org/previous-tasks)
* [SemEval](https://en.wikipedia.org/wiki/SemEval)
* BioNLP [2016](http://2016.bionlp-st.org/), [2013](http://2013.bionlp-st.org/), [2011](http://2011.bionlp-st.org/), [2009](http://www.nactem.ac.uk/tsujii/GENIA/SharedTask/)
* [CHEMDNER](http://www.biocreative.org/tasks/biocreative-iv/chemdner/)
* [ACE2004](https://catalog.ldc.upenn.edu/LDC2005T09)
* [Enron email dataset](https://www.cs.cmu.edu/~./enron/)
* [Citeseer](http://csxstatic.ist.psu.edu/about/data)
* [Reuters](http://www.daviddlewis.com/resources/testcollections/reuters21578/)

## Exercise

Select one of the NLP datasets or extract your own and then:

* Overview its structure.
* Report on dataset features (number of tags, words, sentences, ...)
* Use some existing data source and define some manual rules to tackle the dataset problem. Report on the accuracy of your method (percentage of correct labels) and compare to baseline or existing work.

You can also visualize data using [Matplotlib](http://matplotlib.org/gallery.html).